[package]
name = "cai_api"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
reqwest = { version = "0.12.22", features = ["json"] }
tokio-tungstenite = { version = "0.27.0", features = ["native-tls"] }
